FORMAT: 1A
HOST: http://localhost:1317

# BEPSwap StateChain
This documentation outlines the API for the [BEPSwap](bepswap.com) statechain API.

NOTE: This document is a **work in progress**.

# Group Health Check

## Ping [/swapservice/ping]

### Ping [GET]

+ Response 200 (application/json)
    {
        "ping": "pong"
    }


# Group Pools
This section documents the pools API resources.

## Get a Pool [/swapservice/pool/{ticker}]

+ Parameters
    + ticker: "bnb" (required, string) - The ticker of the pool

### Get a Pool [GET]
+ Response 200 (application/json)
    + Attributes (Pool)

## Get Pool List [/swapservice/pools]

### Get Pools [GET]
+ Response 200 (application/json)
    + Attributes (array[Pool])

## Get List of stakers for a pool [/swapservice/pool/{ticker}/stakers]

+ Parameters
    + ticker: "bnb" (required, string) - The ticker of the pool

### Get Pools [GET]
+ Response 200 (application/json)
    + Attributes (PoolStaker)

## Get List of pools for a staker [/swapservice/staker/{ticker}]

+ Parameters
    + ticker: "bnb" (required, string) - The ticker of the pool

### Get Pools [GET]
+ Response 200 (application/json)
    + Attributes (StakerPool)


# Group Tx

## Get a Tx [/swapservice/tx/{hash}]

+ Parameters
    + ticker: "E17A0906E015F0C343691C18E475C8CB5F3F6C63F5BCDE0F3A341909763CC92B" (required, string) - Tx hash of a binance transaction

### Get TX Information [GET]
+ Response 200 (application/json)
    + Attributes (Tx)



## Data Structures

### Pool
+ balance_rune: Amount of rune the pool has
+ balance_token: Amount of token the pool has
+ ticker: the ticker of the non-rune token
+ pool_units: total number of units within the pool
+ status: the status of the pool

### PoolStaker
+ ticker: the ticker of the non-rune token
+ total_units: the total number of units of the pool
+ stakers: (array[StakerUnit]) a list of stakers in this pool

### StakerUnit
+ staker_id: bnb address of the staker
+ units: amount of units staked

### StakeTxDetail
+ request_tx_hash: the binance tx has of the request
+ rune_amount: the amount of rune
+ token_amount: the amount of token 

### StakerPoolItem
+ ticker: the ticker of the non-rune token
+ units: the amount of units
+ stake_details: (array[StakeTxDetail]) a list of stake tx details

### StakerPool
+ staker_id: the bnb address of the staker
+ pool_and_units: list of pools and their stake details

### Tx
+ request: request tx hash
+ status: status of tx
+ done: completed tx hash
+ sender: bnb address of requester
